Config = {}

Config.Locale = 'pl'

Config.pedList = {
------ GTA-V SP -------
	'player_zero',
	'player_one',
	'player_two',
------ K-9 POLICE -----
	'a_c_shepherd',
------ Dziadek --------
	'a_m_o_genstreet_01',
------ Bloods Fat -----
	'ExileRP_bloodsfat',
------ Dzieciaki ------
	'ExileRP_Dziecko0',
	'ExileRP_Dziecko1',
	'ExileRP_Dziecko2',
	'ExileRP_Dziecko3',
	'ExileRP_Dziecko4',
	'ExileRP_Dziecko5',
	'ExileRP_Dziecko6',
	'ExileRP_Dziecko7',
	'ExileRP_Dziecko8',
	'ExileRP_Dziecko9',
	'ExileRP_Dziecko10',
	'ExileRP_Dziecko11',
	'ExileRP_Dziecko12',
	'ExileRP_Dziecko13',
	'ExileRP_Dziecko14',
	'ExileRP_Dziecko15',
	'ExileRP_Dziecko16',
	'ExileRP_Dziecko17',
	'ExileRP_Dziecko18',
	'ExileRP_Dziecko19',
	'ExileRP_Dziecko20',
	'ExileRP_Dziecko21',
	'ExileRP_Dziecko22',
	'ExileRP_Dziecko23',
	'ExileRP_Dziecko24',
	'ExileRP_Dziecko25',
	'ExileRP_Dziecko26',
	'ExileRP_Dziecko27',
	'ExileRP_Dziecko28',
------ Zwierzęta ------
	'ExileRP_rhesus',
	'ExileRP_racoon',
	'a_c_chop',
	'a_c_pit_exilerp',
	'a_c_chimp',
	'a_c_horse',
	'a_c_panther',
	'a_c_rabbit_01',
	'a_c_sloth',
	'a_c_husky',
	'a_c_retriever',
	'a_c_mtlion',
	'a_c_boar',
	'a_c_cow',
	'a_c_coyote',
	'a_c_deer',
	'a_c_mtlion',
	'a_c_pig',
	'a_c_elephant',
------ EVENTS ---------
	'exile_f_character_select',
	'exile_m_character_select',
	'Santaclaus',
	'Hulk1',
	'Hulk2',
	'chucky',
	'Ironman',
	'Mr_kebun',
	's_m_y_joker',
	's_m_m_snow',
	's_m_y_bovice',
	's_m_y_happy',
	'a_m_m_taco_kid',
	'silverhand',
	'davidwonders',
	'francis_g_francer',
	'francis_small_francer',
	'ig_francis',
	'ig_abdulsquid',
	'ig_mike',
	'ig_myers',
	'ig_rabies',
	'ig_sayeed_w',
	'ig_squid',
	'ig_speedy',
	'ig_shevy',
	'ig_siz_fat',
	'ghostface',
	'mando',
	'walter',
	'z_sprinkle',
	'igor',
	'jason',
	'k_fatrandy',
	'lilfatrandy',
	'np_nancy',
	'p_e_d_ott',
	'pelerynka',
	'ramee',
	'koil',
	'ig_trafficwarden_m',

}