Config.Sitable = {

	-- BAR
	v_club_bahbarstool 			= { scenario = 'PROP_HUMAN_SEAT_BAR', verticalOffset = -0.30, forwardOffset = 0.0, leftOffset = 0.0, sitting = false},
	v_club_baham_bckt_chr 		= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.1, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	v_club_stagechair 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	v_club_barchair 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},

	-- BENCH
	prop_bench_01a 				= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_bench_01b 				= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.45, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_bench_01c 				= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.45, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_bench_02 				= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_bench_03 				= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.45, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_bench_04 				= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_bench_05 				= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.43, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_bench_06 				= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_bench_08 				= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_bench_09 				= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.32, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_bench_10 				= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.50, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_bench_11 				= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.43, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_fib_3b_bench 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.48, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_ld_bench01 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_wait_bench_01 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},

	-- CHAIR
	v_serv_ct_chair02 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = 0.0, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	hei_prop_heist_off_chair 	= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	hei_prop_hei_skid_chair 	= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.08, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_chair_01a 				= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_chair_01b 				= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.51, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_chair_02 				= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_chair_03 				= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_chair_04a 				= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_chair_04b 				= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_chair_05 				= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_chair_06 				= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_chair_08 				= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = 0.0, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_chair_09 				= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_chair_10 				= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_chateau_chair_01 		= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.0, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_clown_chair 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_cs_office_chair 		= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_direct_chair_01 		= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.18, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_direct_chair_02 		= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.20, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_gc_chair02 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = 0.0, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_off_chair_01 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_off_chair_03 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_off_chair_04 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.45, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_off_chair_04b 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.45, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_off_chair_04_s 		= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_off_chair_05 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.40, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_old_deck_chair 		= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = 0.13, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_old_wood_chair 		= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.12, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_rock_chair_01 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.12, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_skid_chair_01 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.09, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_skid_chair_02 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.09, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_skid_chair_03 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.09, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_sol_chair 				= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.53, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_wheelchair_01 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.1, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_wheelchair_01_s 		= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.55, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	p_armchair_01_s 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	p_clb_officechair_s 		= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	p_dinechair_01_s 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	p_ilev_p_easychair_s 		= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.55, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	p_soloffchair_s 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = 0.1, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	p_yacht_chair_01_s 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = 0.0, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	v_club_officechair 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	v_corp_bk_chair3 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.51, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	v_corp_cd_chair 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	v_corp_offchair 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	v_ilev_chair02_ped 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = 0.0, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	v_ilev_hd_chair 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.64, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	v_ilev_p_easychair 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.55, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	v_ret_gc_chair03 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = 0.14, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_ld_farm_chair01 		= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_table_04_chr 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.54, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_table_05_chr 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.48, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_table_06_chr 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	v_ilev_leath_chr 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_table_01_chr_a 		= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = 0.0, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_table_02_chr 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_table_03b_chr 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_table_03_chr 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_torture_ch_01 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.12, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	v_ilev_fh_dineeamesa 		= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.55, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	v_ilev_tort_stool 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.15, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	v_ilev_fh_dineeamesa 		= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.52, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	v_res_fh_dineeamesb 		= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.52, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	v_res_fh_dineeamesa 		= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.52, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	v_ilev_fh_kitchenstool 		= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	v_ilev_tort_stool 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},

	-- SEAT
	hei_prop_yah_seat_01 		= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.6, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	hei_prop_yah_seat_02 		= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	hei_prop_yah_seat_03 		= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_waiting_seat_01 		= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_yacht_seat_01 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_yacht_seat_02 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_yacht_seat_03 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.6, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_hobo_seat_01 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.3, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},

	-- COUCH
	prop_rub_couch01 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	miss_rub_couch_01 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_ld_farm_couch01 		= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_ld_farm_couch02 		= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_rub_couch02 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_rub_couch03 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_rub_couch04 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},

	-- SOFA
	p_lev_sofa_s 				= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	p_res_sofa_l_s 				= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	p_v_med_p_sofa_s 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	p_yacht_sofa_01_s 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	v_ilev_m_sofa 				= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	v_res_tre_sofa_s 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	v_tre_sofa_mess_a_s 		= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	v_tre_sofa_mess_b_s 		= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	v_tre_sofa_mess_c_s 		= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},

	-- MISC
	prop_roller_car_01 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.35, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	prop_roller_car_02 			= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.35, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},

	['-70627249']				    = { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	['-721037220']				= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	['-470815620']				= { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = 0.0, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	['-992735415']               = { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = 0.15, forwardOffset = 0.0, leftOffset = 0.0, sitting = true},
	['1085033290']               = { scenario = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER', verticalOffset = 0.1, forwardOffset = 0.0, leftOffset = 0.0, sitting = true}
}